name: html_content_measurer
description: A utility for measuring the height of dynamically rendered HTML content in web applications.
homepage: https://github.com/Tristan-2021/html_content_measurer

version: 1.0.2
# repository: https://github.com/my_org/my_repo

environment:
  # sdk: ^3.6.1
  sdk: ">=3.0.0 <4.0.0"
# Add regular dependencies here.
dependencies:
  # path: ^1.8.0

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
